#!/bin/bash

#=================================================
# COMMON VARIABLES AND HELPERS
#=================================================

# Apply the LDAP authentication configuration directly in Moodle's database.
#
# Moodle exposes no CLI to configure the LDAP auth plugin, so we write the
# relevant rows straight into the (MariaDB) database. Table names have no schema
# prefix on MySQL/MariaDB (unlike the previous PostgreSQL "public." prefix).
#
# Requires: $admin (Moodle admin username), a reachable database ($db_name).
_moodle_configure_ldap() {
    local statements=(
        "UPDATE mdl_config SET value='ldap,email' WHERE name='auth';"
        "UPDATE mdl_config_plugins SET value='ldap://127.0.0.1/' WHERE plugin='auth_ldap' AND name='host_url';"
        "UPDATE mdl_config_plugins SET value='uid' WHERE plugin='auth_ldap' AND name='user_attribute';"
        "UPDATE mdl_config_plugins SET value='ou=users,dc=yunohost,dc=org' WHERE plugin='auth_ldap' AND name='contexts';"
        "UPDATE mdl_config_plugins SET value='givenName' WHERE plugin='auth_ldap' AND name='field_map_firstname';"
        "UPDATE mdl_config_plugins SET value='sn' WHERE plugin='auth_ldap' AND name='field_map_lastname';"
        "UPDATE mdl_config_plugins SET value='mail' WHERE plugin='auth_ldap' AND name='field_map_email';"
        "UPDATE mdl_config_plugins SET value='onlogin' WHERE plugin='auth_ldap' AND (name='field_updatelocal_firstname' OR name='field_updatelocal_lastname' OR name='field_updatelocal_email');"
        "UPDATE mdl_config_plugins SET value='locked' WHERE plugin='auth_ldap' AND (name='field_lock_firstname' OR name='field_lock_lastname' OR name='field_lock_email');"
        "UPDATE mdl_user SET auth='ldap' WHERE username='$admin';"
    )

    local statement
    for statement in "${statements[@]}"; do
        ynh_mysql_db_shell "$db_name" <<< "$statement"
    done
}

# Ensure config.php declares the Moodle 5.1+ front-controller router as configured.
#
# Moodle 5.1 made the router (reached via r.php) mandatory and checks
# $CFG->routerconfigured in Site admin > Server > Environment. The NGINX config
# already routes non-file requests to r.php (try_files ... /r.php), so the router
# works; we just have to declare it. config.php generated by admin/cli/install.php
# (fresh installs) and config.php kept across upgrades don't carry the flag, so
# inject it before the lib/setup.php require. Idempotent.
#
# Requires: $install_dir.
_moodle_ensure_routerconfigured() {
    local config="$install_dir/config.php"
    [ -f "$config" ] || return 0

    # Already an active "= true" assignment (not a comment/false)? Nothing to do.
    if grep -qE '^[[:space:]]*\$CFG->routerconfigured[[:space:]]*=[[:space:]]*true[[:space:]]*;' "$config"; then
        return 0
    fi

    # We are about to modify config.php. Back up first if it differs from the
    # stored checksum, so an administrator's customizations aren't silently lost
    # (and a later change_url can still detect them against the new baseline).
    ynh_backup_if_checksum_is_different "$config"

    if grep -qE '^[[:space:]]*\$CFG->routerconfigured[[:space:]]*=' "$config"; then
        # An assignment exists but isn't "true" (e.g. false) — force it to true.
        sed -i -E 's/^([[:space:]]*\$CFG->routerconfigured[[:space:]]*=[[:space:]]*).*/\1true;/' "$config"
    else
        # No assignment at all — insert one before the lib/setup.php require.
        sed -i '/require_once.*lib\/setup\.php/i $CFG->routerconfigured = true;' "$config"
    fi

    ynh_store_file_checksum "$config"
}

# Composer version used to install Moodle's runtime dependencies.
composer_version="2.8.9"

# Install Moodle's Composer runtime dependencies into vendor/.
#
# Since Moodle 5.1/5.2 many runtime libraries (guzzle, phpmailer, adodb,
# htmlpurifier, slim, aws-sdk, ...) ship only via Composer. The GitHub source
# tarball gitignores vendor/, so it must be (re)populated after every
# ynh_setup_source (which --full_replace otherwise wipes it). This is exactly
# what Moodle's "Composer installed data" environment check asks for
# (composer install --no-dev --classmap-authoritative). composer.json and
# composer.lock live at the install_dir root (the web code is under public/).
#
# Requires: $install_dir, $php_version. Runs as the app user (ynh_composer_exec).
_moodle_composer_install() {
    ynh_composer_install
    ynh_composer_exec install --no-dev --classmap-authoritative --prefer-dist --no-progress
    # The phar isn't needed at runtime (and isn't under public/, so never served).
    ynh_safe_rm "$install_dir/composer.phar"
}
